version: '3.8'

services:
  backend:
    command: ["/usr/local/bin/wait-for-it.sh", "${POSTGRES_HOST}:${POSTGRES_PORT}", "--", "npm", "run", "start"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - backend-network

  postgres:
    image: postgres:13
    container_name: nest-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
